#!/bin/bash
#This script will download the packages necessary for GUI mode

sudo xbps-remove vim
sudo xbps-install -S w3m python-pip xorg i3-gaps i3status i3lock dmenu rxvt-unicode screenFetch scrot feh ffmpeg ImageMagick gvim qutebrowser dbus
sudo pip install pywal
