#!/bin/bash
#This script preparates the system and move the dotfiles to the system
#Should only be used once in every machine

mkdir ~/Code
mkdir ~/Documents
mkdir ~/Downloads
mkdir ~/Mail
mkdir ~/Programs
mkdir ~/Public
mkdir ~/Repositories
mkdir ~/Scripts
mkdir ~/Templates
mkdir ~/Torrents
mkdir ~/USB
cp 'Cheatsheet' 'Void Packages' ~/Documents
cp .bashrc .bashsys .rtorrent.rc .tmux.conf .vimrc ~/
cp .i3status.conf .xinitrc .Xresources ~/
cp -r .config ~/
cp -r .elinks ~/
cp -r .gnupg ~/
cp -r .mutt ~/
cp -r .newsbeuter ~/
sudo cp issue extrakeys rc.local /etc/
sudo rm -r /var/service/agetty-tty2
sudo rm -r /var/service/agetty-tty3
sudo rm -r /var/service/agetty-tty4
sudo rm -r /var/service/agetty-tty5
sudo rm -r /var/service/agetty-tty6
sudo xbps-install -S base-devel alsa-utils gdb gnupg2 python wget zip tlp ufw tmux vim ranger nnn elinks mutt irssi rsync rtorrent mpd ncmpcpp newsbeuter calcurse htop iftop iotop powertop nethogs rkhunter cmatrix cyrus-sasl-modules
sudo ln -s /etc/sv/ufw /var/service/
sudo ln -s /etc/sv/tlp /var/service/
cd ~/
mv tide ~/Repositories
